version: '3.7'

services:
    apache:
        build: 
          context: ./
        ports:
            - 80:80
            - 443:443
        volumes:
            - "./:/var/www/html"
    db:
        image: mariadb:10.5.2
        volumes:
            - db-volume:/var/lib/mysql
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "mutillidae"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'mutillidae'
            MYSQL_DATABASE: 'mutillidae'


volumes:
    db-volume:   